[pytest]
console_output_style = count
minversion = 7.0
python_files = test_*.py
testpaths = tests/
# Note: register new markers via src/execution_testing/cli/pytest_commands/plugins/shared/execute_fill.py
addopts =
    -p execution_testing.cli.pytest_commands.plugins.shared.execute_fill
    -p execution_testing.cli.pytest_commands.plugins.shared.live_client_flags
    -p execution_testing.cli.pytest_commands.plugins.execute.execute
    -p execution_testing.cli.pytest_commands.plugins.forks.forks
    -p execution_testing.cli.pytest_commands.plugins.execute.execute_flags.execute_flags
    -p execution_testing.cli.pytest_commands.plugins.concurrency
    -p execution_testing.cli.pytest_commands.plugins.execute.sender
    -p execution_testing.cli.pytest_commands.plugins.execute.pre_alloc
    -p execution_testing.cli.pytest_commands.plugins.shared.benchmarking
    -p execution_testing.cli.pytest_commands.plugins.shared.transaction_fixtures
    -p execution_testing.cli.pytest_commands.plugins.execute.rpc.remote_seed_sender
    -p execution_testing.cli.pytest_commands.plugins.execute.rpc.remote
    -p execution_testing.cli.pytest_commands.plugins.help.help
    -p execution_testing.cli.pytest_commands.plugins.custom_logging.plugin_logging
    --tb short
    --dist load
    --ignore tests/cancun/eip4844_blobs/point_evaluation_vectors/
    --ignore tests/json_loader
    --ignore tests/spec_tools

    # Run On Hedera: Raises internal error at `pre.deploy_contract`: 'initcode prefix too long' but this test can be safely skipped https://github.com/gkozyryatskyy/execution-spec-tests/issues/22
    --deselect tests/frontier/precompiles/test_precompile_absence.py

    # Run On Hedera: `SELFDESTRUCT`ing a contract with funds is not supported in Hedera https://github.com/gkozyryatskyy/execution-spec-tests/issues/29
    --deselect tests/paris/security/test_selfdestruct_balance_bug.py

    # Run On Hedera: Hedera does not support EIP-4895; these tests can be safely skipped https://github.com/gkozyryatskyy/execution-spec-tests/issues/23
    --deselect tests/shanghai/eip4895_withdrawals/

    # Run On Hedera: Not supported in Hedera https://github.com/gkozyryatskyy/execution-spec-tests/issues/20
    --deselect tests/cancun/eip1153_tstore/test_tstorage_selfdestruct.py

    # Run On Hedera: There is no beacon root contract in Hedera https://github.com/gkozyryatskyy/execution-spec-tests/issues/19
    --deselect tests/cancun/eip4788_beacon_root/

    # Run On Hedera: Unable to run test due to AssertionError: Transaction type 3 is not supported in execute mode https://github.com/gkozyryatskyy/execution-spec-tests/issues/21
    --deselect tests/cancun/eip4844_blobs/test_blob_txs.py
    --deselect tests/cancun/eip4844_blobs/test_blob_txs_full.py
    --deselect tests/cancun/eip4844_blobs/test_blobhash_opcode.py
    --deselect tests/cancun/eip4844_blobs/test_excess_blob_gas.py

    # Run On Hedera: Hedera does not support EIP-6780 https://github.com/gkozyryatskyy/execution-spec-tests/issues/24
    --deselect tests/cancun/eip6780_selfdestruct/

    # Run On Hedera:
    # EIP-7600(Pectra) includes EIP-2537, EIP-2935, EIP-6110, EIP-7002, EIP-7251, EIP-7549, EIP-7623, EIP-7685, EIP-7691, EIP-7702
    # Hedera supports EIP-2537, EIP-7623, EIP-7702 as part of its Prague Upgrade
    # https://github.com/hiero-ledger/hiero-consensus-node/issues/20043
    # https://hips.hedera.com/hip/hip-1341#hip-1341
    # Run On Hedera: L2 related issues are not applicable to Hedera
    --deselect tests/prague/eip2935_historical_block_hashes_from_state/
    # Run On Hedera: Eth2 validator related issues are not applicable to Hedera
    --deselect tests/prague/eip6110_deposits/
    --deselect tests/prague/eip7002_el_triggerable_withdrawals/
    --deselect tests/prague/eip7251_consolidations/
    --deselect tests/prague/eip7685_general_purpose_el_requests/